In [4]:
#question 1
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
mnist = load_digits(n_class=10)

In [5]:
#question 2
x=mnist.data
y=mnist.target

In [6]:
pd.DataFrame(x)

0    1     2     3     4     5     6    7    8     9  ...     54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0 ...    9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
5     0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0 ...    4.0  0.0   
6     0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
7     0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0 ...    0.0  0.0   
8     0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
9     0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0 ...    4.0  0.0   
10    0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
11    0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    0.0  0.0   
12    0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  2.0   
13    0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0 ...    6.0  0.0   
14    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
15    0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0 ...    0.0  0.0   
16    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
17    0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
18    0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
20    0.0  0.0   3.0  13.0  11.0   7.0   0.0  0.0  0.0   0.0 ...    1.0  0.0   
21    0.0  0.0   0.0   2.0  16.0  16.0   2.0  0.0  0.0   0.0 ...    2.0  0.0   
22    0.0  0.0   8.0  16.0   5.0   0.0   0.0  0.0  0.0   1.0 ...    3.0  0.0   
23    0.0  1.0   8.0  12.0  15.0  14.0   4.0  0.0  0.0   3.0 ...    0.0  0.0   
24    0.0  0.0   0.0   0.0  12.0   2.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
25    0.0  0.0  12.0   8.0   8.0   7.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
26    0.0  0.0   1.0  13.0  14.0   3.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
27    0.0  0.0   0.0   8.0  14.0  14.0   2.0  0.0  0.0   0.0 ...    0.0  0.0   
28    0.0  0.0  10.0  11.0   4.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
29    0.0  0.0   9.0  13.0   7.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...   ... ...    ...  ...   
1767  0.0  0.0   0.0   2.0  16.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1768  0.0  0.0   5.0  16.0  10.0   0.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
1769  0.0  0.0   9.0  12.0  14.0   6.0   0.0  0.0  0.0   0.0 ...    2.0  0.0   
1770  0.0  2.0  10.0  12.0  16.0   8.0   0.0  0.0  0.0   4.0 ...    5.0  0.0   
1771  0.0  0.0   0.0   6.0  12.0   6.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1772  0.0  0.0   5.0  14.0  11.0   8.0   0.0  0.0  0.0   4.0 ...    0.0  0.0   
1773  0.0  0.0   2.0  13.0  10.0   0.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1774  0.0  0.0   6.0  12.0  12.0   6.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1775  0.0  0.0   6.0  16.0  16.0   3.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1776  0.0  0.0  12.0  16.0  16.0   7.0   0.0  0.0  0.0   3.0 ...    7.0  0.0   
1777  0.0  0.0   0.0   2.0  14.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1778  0.0  0.0   0.0   1.0  13.0   8.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1779  0.0  0.0   3.0  10.0  16.0  16.0   4.0  0.0  0.0   0.0 ...    0.0  0.0   
1780  0.0  3.0  14.0  15.0   6.0   0.0   0.0  0.0  0.0   7.0 ...    6.0  0.0   
1781  0.0  0.0  10.0  16.0  14.0   5.0   0.0  0.0  0.0   2.0 ...    1.0  0.0   
1782  0.0  1.0  10.0  13.0   2.0   0.0   0.0  0.0  0.0  10.0 ...   13.0  0.0   
1783  0.0  0.0  15.0  13.0   1.0   0.0   0.0  0.0  0.0   0.0 ...   14.0  0.0   
1784  0.0  0.0   1.0  10.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    2.0  0.0   
1785  0

In [7]:
pd.DataFrame(y)

0
0     0
1     1
2     2
3     3
4     4
5     5
6     6
7     7
8     8
9     9
10    0
11    1
12    2
13    3
14    4
15    5
16    6
17    7
18    8
19    9
20    0
21    1
22    2
23    3
24    4
25    5
26    6
27    7
28    8
29    9
...  ..
1767  4
1768  0
1769  5
1770  3
1771  6
1772  9
1773  6
1774  1
1775  7
1776  5
1777  4
1778  4
1779  7
1780  2
1781  8
1782  2
1783  2
1784  5
1785  7
1786  9
1787  5
1788  4
1789  8
1790  8
1791  4
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [8]:
#question 3
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

C:\Users\AMBER1\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [9]:
#question4
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)


In [10]:
#question 5
from sklearn import model_selection
scoring='accuracy'
results=model_selection.cross_val_score(classifier,x,y,scoring=scoring)

In [11]:
results.mean()

0.91822044596985819

In [12]:
scoring='neg_log_loss'
results=model_selection.cross_val_score(classifier,x,y,scoring=scoring)
results

array([-0.44884352, -0.21132308, -0.56637829])

In [13]:
scoring='r2'
results=model_selection.cross_val_score(classifier,x,y,scoring=scoring)
results

array([ 0.76663125,  0.83413775,  0.67047827])

0.8 will be the more fit value

In [14]:
scoring='neg_mean_absolute_error'
results=model_selection.cross_val_score(classifier,x,y,scoring=scoring)
print("MAE: %.3f(%.3f)" %(results.mean(),results.std()))

MAE: -0.351(0.090)


In [15]:
scoring='neg_mean_squared_error'
results=model_selection.cross_val_score(classifier,x,y,scoring=scoring)
print("MAE: %.3f(%.3f)" %(results.mean(),results.std()))

MAE: -1.994(0.552)


In [17]:
from sklearn.metrics import confusion_matrix
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[45  0  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  2  0  3  0]
 [ 0  0 51  2  0  0  0  0  0  0]
 [ 0  0  1 52  0  0  0  0  0  1]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  1  0  0  0 55  1  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  1  0  1  1  0  0 50  0  0]
 [ 0  3  1  0  0  0  0  0 55  2]
 [ 0  0  0  1  0  1  0  0  2 53]]


In [18]:
from sklearn.metrics import classification_report
cm=classification_report(y_test,y_pred)
print(cm)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        45
          1       0.89      0.90      0.90        52
          2       0.96      0.96      0.96        53
          3       0.93      0.96      0.95        54
          4       0.98      1.00      0.99        48
          5       0.98      0.96      0.97        57
          6       0.95      0.98      0.97        60
          7       1.00      0.94      0.97        53
          8       0.92      0.90      0.91        61
          9       0.95      0.93      0.94        57

avg / total       0.95      0.95      0.95       540

