# question 1
p(yes|sunny)=(p(sunny|yes) * p(yes))/p(sunny)
            =(3/5 * 9/14)/(5/14)
            =1

In [1]:
#question 2
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

In [7]:
x=iris.data
y=iris.target

In [16]:
y=y.reshape(150,1)

In [17]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

C:\Users\AMBER1\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [21]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x,y)
y_pred=model.predict(x_test)

C:\Users\AMBER1\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [24]:
print(metrics.classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45



In [26]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x,y)
y_pred=model.predict(x_test)

C:\Users\AMBER1\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,y_pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [28]:
print(metrics.classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        16
          1       1.00      0.94      0.97        18
          2       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45

